phrases = [
    "Done",
    "done",
    "lfg",
    "Lfg",
    "Lfg",
    "Lfg 🚀❤️",
    "Go",
    "Me",
    "meee",
    "Good Luck",
    "Gl",
    "Lets go",
    "gooooo",
    "Nice!",
    "LFG",
    "LFG SIR",
    "happy",
    "Lfg sir ❤️",
    "Wooww",
    "LFGGGG.....",
    "Lfg🔥",
    "Lesssssgooo"
]
done_templates = ["Done",
                  "done",
                  "DONE",
                  "Done",
                  "done sir",
                  "Dine Sir",
                  "Done✅",
                  "DONE✅",
                  "donee",
                  "done✅",
                  "Done✔",
                  "done ☑",
                  "done",
                  "Done",
                  "done",
                  "done",
                  "done",
                  "done",
                  "done",
                  "done",
                  "Done",
                  "Done",
                  "Done",
                  "Done",
                  "Done",
                  "Done",
                  "Done",
                  "done sir",
                  "Done Sir",
                  "Done",
                  "done"]
